#%RAML 1.0
title: ecommerceSuiteDatabaseSystemApi2


uses:
  library: fragments/library.raml

/users:
  post:
    body:
      application/json:
        library.postUserRequestBody
  get:
    is: [library.getUsersByEmail]
  /{userId}:
    get:
  /getByRole:
    get:
      is: [library.getUsersByRole]

  
/stores:
  post:
    body:
      application/json:
        library.postStoresRequestBody
  /{storeId}:
    patch:
      body:
        application/json:
          library.patchStoresRequestBody
    get:
  get:
    is: [library.getStoresByUserId]
  /verificationStatus:
    get:
      is: [library.getStoresByVerificationStatus]

/products:
  post:
    body:
      application/json:
        library.postProductRequestBody
  get:
    is: [library.getProductsByFilters]
  /{productId}:
    get:
    patch:
      body:
        application/json:
          library.patchProductRequestBody
    delete:
    
/carts:
  post:
    body:
      application/json:
        library.postCartRequestBody
  delete:
    is: [library.deleteCartByFilters]
  get:
    is: [library.getCartByFilters]
  /{cartItemId}:
    get:
    patch:
      body:
        application/json:
          library.patchCartRequestBody

/orders:
  post:
    body:
      application/json:
        library.postOrderRequestBody
  get:
    is: [library.getOrdersByUserId]
  /{orderId}:
    get:
    /cancellation:
      patch:
    /paymentStatus:
      patch:
        body:
          application/json:
            properties:
              paymentStatus:
                type: string
  /paymentStatus:
    get:
      queryParameters:
        paymentStatus:
          type: string
          enum: ["pending", "reversed", "success"]
                
      

/orderItems:
  post:
    body:
      application/json:
        library.postOrderItemsRequestBody
  /storeId:
    get:
      is: [library.getOrderItemsByStoreId]
  /orderId:
    get:
      is: [library.getOrderItemsByOrderId]

